from .chat_template import (
    alpaca_template,
    amberchat_template,
    chatml_template,
    chatqa_template,
    falcon_template,
    gemma_template,
    llama_2_template,
    llama_3_template,
    mistral_template,
    openchat_template,
    phi_3_template,
    saiga_template,
    solar_template,
    vicuna_template,
    zephyr_template,
)
